<div class="col-4-1 last">
                      <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_QHDCPM134354M4" class="qhd_column_contain"><!-- Start_Module_134357 --><a name="25088" id="25088"></a><!-- S module-default -->
                        <div class="module-default module-box">
                          <div class="module-inner">
                            <div class="module-title module-title-img"><img src="/skin/img/2ca64124-ca35-4728-b28c-abb28a90b2d6_250_250.jpg" alt="[field:typename /]" /></div>
                            <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_ctr134357134357_mainArea" class="module-content"><!-- Start_Module_134357 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><strong><span style="font-size:16px;">[field:typename /]</span></strong></a><br />
                                  <span style="font-family: Consolas, 'Lucida Console', monospace; font-size: 12px; line-height: normal; white-space: pre-wrap; widows: 1;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_134357 --></div>
                          </div>
                        </div>
                        <!-- E module-default --></div>
                    </div>