<div class="col-4-1">
                      <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_QHDCPM134354M3" class="qhd_column_contain"><!-- Start_Module_134358 --><a name="25087" id="25087"></a><!-- S module-default -->
                        <div class="module-default module-box">
                          <div class="module-inner">
                            <div class="module-title module-title-img"><img src="/skin/img/8afed580-563a-44fb-9c44-b3f841abf0d9_250_250.jpg" alt="[field:typename /]" /></div>
                            <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_ctr134358134358_mainArea" class="module-content"><!-- Start_Module_134358 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><strong><span style="font-size:16px;">[field:typename /]</span></strong></a><br />
                                  <span style="font-family: Consolas, 'Lucida Console', monospace; font-size: 12px; line-height: normal; white-space: pre-wrap; widows: 1;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_134358 --></div>
                          </div>
                        </div>
                        <!-- E module-default --></div>
                    </div>