<div class="headlines-content not-animated" data-animate="fadeInUp" data-delay="200">
                    <p><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" alt="[field:title/]" /></a></p>
                    <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                    <div class="headlines-content-summary">
                      <div class="qhd-content">
                        <p> [field:description function="cn_substr(@me,180)"/]...</p>
                      </div>
                    </div>
                  </div>