<div class="col-4-1">
                      <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_QHDCPM134354M2" class="qhd_column_contain"><!-- Start_Module_134356 --><a name="25086" id="25086"></a><!-- S module-default -->
                        <div class="module-default module-box">
                          <div class="module-inner">
                            <div class="module-title module-title-img"><img src="/skin/img/3be17285-9783-4f55-94ac-ca35fa0ca459_250_250.jpg" alt="[field:typename /]" /></div>
                            <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_ctr134356134356_mainArea" class="module-content"><!-- Start_Module_134356 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><strong><span style="font-size:16px;">[field:typename /]</span></strong></a><br />
                                  <span style="font-family: Consolas, 'Lucida Console', monospace; font-size: 12px; line-height: normal; white-space: pre-wrap; widows: 1;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_134356 --></div>
                          </div>
                        </div>
                        <!-- E module-default --></div>
                    </div>