<div class="col-4-1">
                      <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_QHDCPM134354M1" class="qhd_column_contain"><!-- Start_Module_134355 --><a name="25085" id="25085"></a><!-- S module-default -->
                        <div class="module-default module-box">
                          <div class="module-inner">
                            <div class="module-title module-title-img"><img src="/skin/img/0d1ae6d7-09bf-48a0-a226-a9eda5bcdb63_250_250.jpg" alt="[field:typename /]" /></div>
                            <div id="a1portalSkin_ctr134354134354_Column4C25A25A25A25_ctr134355134355_mainArea" class="module-content"><!-- Start_Module_134355 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><span style="font-size:16px;"><strong>[field:typename /]</strong></span></a><br />
                                  <span style="font-family: Consolas, 'Lucida Console', monospace; font-size: 12px; line-height: normal; white-space: pre-wrap; widows: 1;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_134355 --></div>
                          </div>
                        </div>
                        <!-- E module-default --></div>
                    </div>