<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,440);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",480,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2946,2981);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",4546,4582);
$z[5][4]['filename']="right.htm";
$z[6]=Array("field","",5209,5228);
$z[6][4]['name']="title";
$z[7]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a> ",5345,5421);
$z[8]=Array("field","",5474,5526);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("field","",5742,5760);
$z[9][4]['name']="body";
$z[10]=Array("type","\r\n                        <div class=\"float-right detail-bottom-button\"><a href=\"[field:typeurl /]\">查看更多</a></div>\r\n                        ",5849,6020);
$z[11]=Array("include","",7498,7535);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("include","",7836,7874);
$z[12][4]['filename']="footer1.htm";

?>