<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,440);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",480,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2946,2981);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4641,4699);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n                          <li class=\"\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                          ",5667,5964);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a></li>";
$z[7]=Array("field","",6650,6669);
$z[7][4]['name']="title";
$z[8]=Array("field","",6800,6818);
$z[8][4]['name']="body";
$z[9]=Array("include","",7162,7199);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("include","",7500,7538);
$z[10][4]['filename']="footer1.htm";

?>