<?php
$z[0]=Array("global","\r\n                      \$a=\"\r\n                      <li class='col-4-1 last not-animated' data-animate='fadeInUp' >\";\r\n                        \$b=\"\r\n                      \r\n                      <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                        if ((@me%4)==0 && @me!=16)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",0,437);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",553,568);
$z[2]=Array("picname","",596,612);
$z[3]=Array("title","",657,671);
$z[4]=Array("arcurl","",785,800);
$z[5]=Array("title","",819,833);

?>