<?php
$z[0]=Array("global","\r\n                      \$a=\"\r\n                      <li class='col-3-1 last not-animated' data-animate='fadeInUp' >\";\r\n                        \$b=\"\r\n                      \r\n                      <li class='col-3-1 not-animated' data-animate='fadeInUp'>\";\r\n                        if ((@me%3)==0 && @me!=12)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",0,437);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",500,515);
$z[2]=Array("title","",524,538);
$z[3]=Array("picname","",550,566);
$z[4]=Array("title","",610,624);
$z[5]=Array("arcurl","",797,812);
$z[6]=Array("title","",822,836);
$z[7]=Array("title","",838,852);

?>