<div class="post-list-item clearfix">
                    <div class="post-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" style="width: 373px; height: 261px;"  alt="[field:title/]"/><span></span><i></i></a></div>
                    <div class="post-text-box light-box">
                      <div class="post-text">
                        <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                        <div class="post-text-summary">
                          <div class="qhd-content">
                            <p>[field:description function="cn_substr(@me,180)"/]...</p>
                          </div>
                        </div>
                      </div>
                      <em class="post-arrow"></em></div>
                  </div>