<?php
$z[0]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",1411,1638);
$z[0][4]['typeid']="1";
$z[0][4]['reid']="1";
$z[0][4]['type']="son";
$z[0][4]['noself']="yes";
$z[1]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",2806,3033);
$z[1][4]['typeid']="9";
$z[1][4]['reid']="9";
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",4201,4430);
$z[2][4]['typeid']="14";
$z[2][4]['reid']="14";
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("global","",6351,6377);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",6383,6407);
$z[4][4]['name']="cfg_beian";

?>