<?php
$z[0]=Array("global","",331,357);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",398,427);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",467,497);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",2902,2937);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",9883,9911);
$z[4][4]['name']="content";
$z[5]=Array("include","",10169,10206);
$z[5][4]['filename']="footer.htm";
$z[6]=Array("include","",10507,10545);
$z[6][4]['filename']="footer1.htm";

?>