<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2960,2995);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",4777,4813);
$z[5][4]['filename']="right.htm";
$z[6]=Array("list","\r\n                    <div class=\"accordion-handle\">\r\n                      <h4>[field:title/]</h4>\r\n                      <i></i></div>\r\n                    <div class=\"accordion-pane\">\r\n                      <div class=\"qhd-content\">\r\n                        <p> [field:body/]</p>\r\n                      </div>\r\n                    </div>\r\n                    ",5355,5773);
$z[6][4]['titlelen']="80";
$z[6][4]['addfields']="body";
$z[7]=Array("include","",6051,6088);
$z[7][4]['filename']="footer.htm";
$z[8]=Array("include","",6389,6427);
$z[8][4]['filename']="footer1.htm";

?>